### ISSUE TITLE
invalid source release 17 with --enable-preview

### ISSUE THREAD

**Issue by lvl100-one** [Apress/java-17-for-absolute-beginners#2]
Hello,

I've got following error when trying to run command 'mvn clean install' -- failure at CHAPTER 07:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project chapter07: Compilation failure
[ERROR] invalid source release 17 with --enable-preview
[ERROR]   (preview language features are only supported for release 20)
```

'mvn --version' returns: 
```
Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)
Maven home: /usr/local/Cellar/maven/3.9.3/libexec
Java version: 20.0.1, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/20.0.1/libexec/openjdk.jdk/Contents/Home
```

BR,

**Comment by smspie** [comment]
Hi, I encountered the same problem and I think it is because you are trying to install the project with java 20, not java 17.

Open the project in IntelliJ IDEa. Under "File" on the top left select "Project Structure", under the "SDK:" drop-down menu select "Add JDK" then "Download JDK". Under "Version:" select "17" and any vendor should work, then click "Download" and "Apply" under the "Project Structure" window.

Now under the "Maven" window under "Lifecycle" try double clicking "install" and it should build the project without failure.

Cheers,

**Comment by lvl100-one** [comment]
Hi,

As a workaround I've changed in my file **pom.xml** Java version lines to

```
<!--  Java version-->
        <maven.compiler.release>20</maven.compiler.release>
        <maven.compiler.source>20</maven.compiler.source>
        <maven.compiler.target>20</maven.compiler.target>
```

After this I've got :
```
 [INFO] BUILD SUCCESS
```

Thx anyway,
Cheers,
